apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: newrelic-logging
  namespace: default
  labels:
    k8s-app: newrelic-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    name: newrelic-logging
spec:
  selector:
    matchLabels:
      name: newrelic-logging
  template:
    metadata:
      labels:
        k8s-app: newrelic-logging
        version: v1
        kubernetes.io/cluster-service: "true"
        name: newrelic-logging
    spec:
      serviceAccountName: newrelic-logging
      containers:
      - name: newrelic-logging
        env:
          - name: ENDPOINT
            value : "https://log-api.newrelic.com/log/v1"
          - name: SOURCE
            value: "kubernetes"
          - name: LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-secret
                key: new_relic_license_key
          - name: BUFFER_SIZE
            value: "256000"
          - name: MAX_RECORDS
            value: "500"
          - name: LOG_LEVEL
            value: "info"
          - name: PATH
            value: "/var/log/containers/*.log"
        image: newrelic/newrelic-fluentbit-output:1.1.2
        command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc/fluent-bit.conf
          - -e
          - /fluent-bit/bin/out_newrelic.so
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc
        - name: varlog
          mountPath: /var
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var
